### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by brainstormapps** [marsbroshok/face-replace#1]
HI, I installed all dependencies required for your project as per following detail
1. python 2.7.12
2. OpenCV 3.1.0
3. Skimage
4. Numpy
5. Dlib 19.1.0 using
sudo apt-get install python-opencv
sudo apt-get install libboost-python-dev cmake
apt install python-pip
pip install dlib
pip install scikit-image

All C++ examples in dlib example folder are running perfectly.
But python examples crash with error: "illegal instructions: (core dumped)"
same happen when i try to run "face-replace" command.

I now it is dependencies installation issue. Can u guid me in detail for installation. I am new in ubuntu.
Thanks and regards

**Comment by marsbroshok** [comment]
Hi, 
There are 2 points you should pay attention:

1. I tested that script with the following versions:
- Python 2.7
- OpenCV 2.4.10
- Skimage
- Numpy
- Dlib library 18.17
- Dlib face shape predictor (68 face landmarks)

It is known that OpenCV 3 changed significantly vs OpenCV 2, so I recommend go with OpenCV 2.

2. I personally never succeeded with Dlib installed with `pip`, I was able to use only compiled from sources version. So it could be the issue as well. 

Good luck!
