### ISSUE TITLE
Where Does Face Masking Occur?

### ISSUE THREAD

**Issue by jacobholiday** [marsbroshok/face-replace#2]
In which part of your code is the source face cut out before warping onto the destination image?

**Comment by marsbroshok** [comment]
Hi, there is no special code for cutting image out. When you pass the new coodinates in that part of the code:
```
warp_trans = skimage.transform.PiecewiseAffineTransform()
warp_trans.estimate(dst_face_coord, src_face_coord)
warped_face = skimage.transform.warp(src_face, warp_trans, output_shape=output_shape)
```
its output has the transformed object and black mask around it. 

Have a look at example here: https://scikit-image.org/docs/dev/auto_examples/transform/plot_piecewise_affine.html

**Comment by tjusxh** [comment]
the link can't visit.

**Comment by marsbroshok** [comment]
@tjusxh thank you, I fix the link in my comment. New link is https://scikit-image.org/docs/dev/auto_examples/transform/plot_piecewise_affine.html
