### ISSUE TITLE
Face mask rendering

### ISSUE THREAD

**Issue by brainstormapps** [marsbroshok/face-replace#3]
Hi,
I want to develop an android app like msqrd. I have developed face detection, face tracking and face swaping using opencv and dlib. No i want to develop face substitution on live camera of android. I think if u give me your python code in C++ I can understand and implement easily for android. Can u help me for it Or give me detailed idea about face mask rendering on tracking face in android.
Thanks and regards
Nadeem Asif

**Comment by marsbroshok** [comment]
Hi,
Sorry, I don't have a C++ version of that code, but I recommend you to google for "C++ affine transformation". That's what you need to wrap mask around the face.

Good luck!
Alexander.

**Comment by brainstormapps** [comment]
Thanks, I have done it already.
