### ISSUE TITLE
About GRAY2BGR does not working...

### ISSUE THREAD

**Issue by seonghun0312** [marsbroshok/face-replace#4]
hey, nice project you made. This helped me a lot. But I have one little issue here. it seems in webcam part, 
`frame_out = cv2.cvtColor(frame_out, cv2.COLOR_GRAY2BGR)`
is not working at all. it's all just gray when I see the result...
I know it's been a year, but could you give me a hand? thanks!

**Comment by marsbroshok** [comment]
Hello, `cv2.cvtColor(frame_out, cv2.COLOR_GRAY2BGR)` converts image into format, compatible with video output. Because processed image is always grayscale, this conversion does not add any colour, just change internal image representation so we can save it in video.
