### ISSUE TITLE
How can use this library for iOS project

### ISSUE THREAD

**Issue by sumitmundra** [marsbroshok/face-replace#6]
Hello Sir,

How can i use this library for iOs project. you can provide me any lib file so i can use it.

**Comment by marsbroshok** [comment]
Hello, check the C++ examples section for DLib library (http://dlib.net) for Face Landmarks detection. You should be able to compile it for iOS and use it with OpenCV. 
I think the tricky part is to wrap new face image, in python I used "skimage.transform" but on iOS I don't know the exact library to do that. Good luck!
